In [ ]:
# 1. Create a NumPy array from [10, 20, 30, 40, 50]. Display its shape, size, and data type.
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr.shape, arr.size, arr.dtype)

(5,) 5 int64


In [ ]:
# 2. Create a 3 × 4 array containing numbers from 1 to 12.
arr2 = np.arange(1, 13).reshape(3, 4)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# 3. Create an array of zeros, an array of ones, and an identity matrix.
print(np.zeros((2,3)))
print(np.ones((2,3)))
print(np.eye(3))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 4. Generate all even numbers between 10 and 50 using np.arange().
print(np.arange(10, 51, 2))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
# 5. Create an array of 10 equally spaced numbers between 0 and 1 using np.linspace().
print(np.linspace(0, 1, 10))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
# 6. Given two NumPy arrays, perform element-wise addition, subtraction, multiplication, and division.
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b, a-b, a*b, a/b)

[5 7 9] [-3 -3 -3] [ 4 10 18] [0.25 0.4  0.5 ]


In [ ]:
# 7. Calculate the square and cube of every element in a NumPy array.
arr=np.array([1,2,3])
squares = arr**2
cube=arr**3
print(squares,cube)

[1 4 9] [ 1  8 27]


In [ ]:
# 8. Increase every element of an array by 15%.
print(a*1.15)

[1.15 2.3  3.45]


In [ ]:
# 10. Create an array from 0 to 20 and extract the first five elements, last five elements, elements from index 5 to 15, and every second element.
arr = np.arange(21)
print(arr[:5], arr[-5:], arr[5:16], arr[::2])

[0 1 2 3 4] [16 17 18 19 20] [ 5  6  7  8  9 10 11 12 13 14 15] [ 0  2  4  6  8 10 12 14 16 18 20]


In [ ]:
# 11. Replace the first five elements of an array with 100.
arr[:5] = 100
print(arr)

[100 100 100 100 100   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20]


In [ ]:
# 12. Create an array and demonstrate the difference between a slice/view and a copy.
arr = np.arange(10)
view = arr[2:6]      # slice/view
copy = arr[2:6].copy()  # copy
view[:] = 99
print(arr,copy)

[ 0  1 99 99 99 99  6  7  8  9] [2 3 4 5]


In [ ]:
# 13. Reverse a NumPy array using slicing.
print(arr[::-1])

[ 9  8  7  6 99 99 99 99  1  0]


In [ ]:
# 14. Create the matrix [[10,20,30],[40,50,60],[70,80,90]]. Extract the second row, third column, and element 50.
matrix = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(matrix[1])       # second row
print(matrix[:,2])     # third column
print(matrix[1,1])     # element 50

[40 50 60]
[30 60 90]
50


In [ ]:
# 15. From the matrix above, extract the sub-matrix [[20,30],[50,60]].
print(matrix[0:2,1:3])

[[20 30]
 [50 60]]


In [ ]:
# 16. Create a 5 × 5 matrix containing 1–25 and extract the first row, last column, middle element, and top-left 3 × 3 matrix.
mat = np.arange(1,26).reshape(5,5)
print(mat[0])          # first row
print(mat[:,-1])       # last column
print(mat[2,2])        # middle element
print(mat[:3,:3])      # top-left 3x3

[1 2 3 4 5]
[ 5 10 15 20 25]
13
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [ ]:
# 17. Create an array containing 1–12 and reshape it into a 3 × 4 matrix.
print(np.arange(1,13).reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# 18. Reshape a 1-D array into a 2 × 5 matrix.
print(np.arange(1,11).reshape(2,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# 19. Convert a 3 × 4 matrix into a 4 × 3 matrix using transpose.
mat = np.arange(1,13).reshape(3,4)
print(mat.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
# 20. Use transpose() and swapaxes() on a 3-D array.
arr3d = np.arange(24).reshape(2,3,4)
print(arr3d.transpose(1,0,2))
print(np.swapaxes(arr3d,0,1))

[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]


In [ ]:
# 21. Create two 3 × 3 matrices and perform element-wise addition and multiplication.
A = np.arange(1,10).reshape(3,3)
B = np.arange(9,0,-1).reshape(3,3)
print(A+B)
print(A*B)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [ ]:
# 22. Calculate the matrix product of two compatible matrices using np.dot().
print(np.dot(A,B))

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
# 23. Find the transpose of a matrix and calculate its dot product with the original matrix.
print(A.T @ A)

[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]


In [ ]:
# 28. Given marks = np.array([35,72,48,90,55,28]), replace marks below 40 with 0 using np.where().
marks = np.array([35,72,48,90,55,28])
print(np.where(marks<40,0,marks))

[ 0 72 48 90 55  0]


In [ ]:
# 29. Given an income array, classify observations as 'High' if income ≥ 50,000 and 'Low' otherwise.
import numpy as np
income = np.array([30000,60000,45000,80000])
print(np.where(income>=50000,'High','Low'))

['Low' 'High' 'Low' 'High']


In [ ]:
# 30. Replace all values greater than 30 in an array with 100 using np.where().
import numpy as np
arr = np.array([10,20,40,50])
print(np.where(arr>30,100,arr))

[ 10  20 100 100]


In [ ]:
# 31. Given a 3×3 matrix, calculate total sum, mean, variance, and standard deviation
import numpy as np
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(a),np.mean(a),np.var(a),np.std(a))

45 5.0 6.666666666666667 2.581988897471611


In [ ]:
# 32. Calculate row‑wise and column‑wise sums using axis
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("Row-wise sums:", matrix.sum(axis=1))     # sum across columns
print("Column-wise sums:", matrix.sum(axis=0))  # sum across rows


Row-wise sums: [ 6 15 24]
Column-wise sums: [12 15 18]


In [ ]:
# 33. Given marks of 10 students, calculate mean, std, min, max
import numpy as np
a= np.array([23,44,25,46,43,12,35,37,29,49])
print(np.mean(a), np.std(a), np.min(a), np.max(a))

34.3 11.269871339105872 12 49


In [ ]:
# 34. Demonstrate difference between any() and all() using Boolean array
import numpy as np
bool_arr = np.array([True,False,True])
print(bool_arr.any())
print(bool_arr.all())

True
False


In [ ]:
#35. Generate 10 random numbers and sort them
import numpy as np
rand_nums= np.random.randint(1,100,10)
print(rand_nums)
print(np.sort(rand_nums))

[20 49 87 43 86 78 26  9 21 14]
[ 9 14 20 21 26 43 49 78 86 87]


In [ ]:
# 36. Given an array with repeated values, find unique elements
import numpy as np
arr = np.array([1,2,3,4,3,4,3,2,2,3,5])
print(np.unique(arr))

[1 2 3 4 5]


In [ ]:
# 37. Given student marks, find unique marks
import numpy as np
marks = np.array([35,72,48,90,55,28,35,72])
print(np.unique(marks))

[28 35 48 55 72 90]


In [ ]:
# 38. Use np.in1d() to check if selected values occur in an array
import numpy as np
a= np.array([2,45,3,5,2,23,55])
selected= np.array([45,3,23,55])
print(np.in1d(selected,a))

[ True  True  True  True]


/tmp/ipykernel_798/2286983893.py:5: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(np.in1d(selected,a))


In [ ]:
# 39. Student Marks Analysis
import numpy as np
marks = np.array([[35,72,48],[90,55,28],[43,76,66],[34,44,96]])
total = marks.sum(axis=1)
average = marks.mean(axis=1)
passed = np.where(average>=55)
print(total,average,passed)


[155 173 185 174] [51.66666667 57.66666667 61.66666667 58.        ] (array([1, 2, 3]),)


In [ ]:
#